// <auto-generated />
using System;
using CogniLens.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CogniLens.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CogniLensDbContext))]
    [Migration("20260725101850_SeedRubrics")]
    partial class SeedRubrics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CogniLens.Core.Entities.Call", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobUri")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Calls");
                });

            modelBuilder.Entity("CogniLens.Core.Entities.JobStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<Guid>("CallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CallId");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("JobStatuses");
                });

            modelBuilder.Entity("CogniLens.Core.Entities.QaReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NextBestAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RubricResultsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SentimentJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CallId")
                        .IsUnique();

                    b.ToTable("QaReports");
                });

            modelBuilder.Entity("CogniLens.Core.Entities.Rubric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Rubrics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            Category = "Opening",
                            Description = "Agent greets the customer professionally and verifies their identity before discussing account details.",
                            IsActive = true,
                            Name = "Greeting and Identity Verification"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            Category = "Soft Skills",
                            Description = "Agent acknowledges the customer's issue, avoids interrupting, and paraphrases the problem back to confirm understanding.",
                            IsActive = true,
                            Name = "Active Listening"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            Category = "Compliance",
                            Description = "Agent reads any legally required disclosure (e.g. call recording notice, terms) verbatim before proceeding.",
                            IsActive = true,
                            Name = "Compliance Disclosure"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            Category = "Resolution",
                            Description = "Agent proposes a concrete resolution or next step that addresses the customer's stated issue.",
                            IsActive = true,
                            Name = "Resolution Offered"
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            Category = "Closing",
                            Description = "Agent summarizes the outcome, confirms the customer has no further questions, and closes the call courteously.",
                            IsActive = true,
                            Name = "Professional Closing"
                        });
                });

            modelBuilder.Entity("CogniLens.Core.Entities.TranscriptSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<int>("SpeakerTag")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CallId", "SequenceNumber");

                    b.ToTable("TranscriptSegments");
                });

            modelBuilder.Entity("CogniLens.Core.Entities.JobStatus", b =>
                {
                    b.HasOne("CogniLens.Core.Entities.Call", "Call")
                        .WithMany("JobStatuses")
                        .HasForeignKey("CallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Call");
                });

            modelBuilder.Entity("CogniLens.Core.Entities.QaReport", b =>
                {
                    b.HasOne("CogniLens.Core.Entities.Call", "Call")
                        .WithOne("QaReport")
                        .HasForeignKey("CogniLens.Core.Entities.QaReport", "CallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Call");
                });

            modelBuilder.Entity("CogniLens.Core.Entities.TranscriptSegment", b =>
                {
                    b.HasOne("CogniLens.Core.Entities.Call", "Call")
                        .WithMany("TranscriptSegments")
                        .HasForeignKey("CallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Call");
                });

            modelBuilder.Entity("CogniLens.Core.Entities.Call", b =>
                {
                    b.Navigation("JobStatuses");

                    b.Navigation("QaReport");

                    b.Navigation("TranscriptSegments");
                });
#pragma warning restore 612, 618
        }
    }
}
